# Generated by Django 5.0.6 on 2024-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='не известно', max_length=100, verbose_name='fio')),
                ('come', models.CharField(default='I cant come', max_length=50, verbose_name='come')),
                ('numberPeople', models.IntegerField(default=0)),
                ('beverages', models.CharField(default='', max_length=50, verbose_name='beverages')),
            ],
        ),
    ]
